accounts/urls.py
from django.urls import path,re_path
from .views import *
from django.contrib.auth import views as auth_views
app_name = 'accounts'
urlpatterns = [
    # path(r'^company-edit/$', company_edit_view, name='company-edit'),
	path('register/',register,name="register"),
    path('login/', login_view, name='login'),
    # path(r'^update-profile/$', update_profile_view, name='update_profile_view'),
    # path(r'^my-account/$',account_view,name="account_view"),
    # path(r'^user-list/$',user_list_view,name="user_list_view"),
    # path(r'^user/(?P<slug>.*)/$', user_update, name='user_update'),
    path('logout/',logout_view,name='logout'),
    path('activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/',
        activate, name='activate'),
]

product/urls.py
from django.urls import path
from product.views import *

app_name = "product"
urlpatterns = [
    path('',index_view,name="index"),
    path('api_view',view_api,name="view_api"),
    path('api_view/<id>/',detail_api,name="detail_api"),
    path('product_detail/<slug>/',product_detail,name="product_detail"),
    path('product_delete/<id>/',delete_product,name="delete_product"),
    path("wish/",wishlist_view, name="wish"),
    path('user_wishlist/',wishlist_product_view,name="user_wishlist"),
    path('cart/', show_cart, name='showcart'),
    path('pluscart/', plus_cart),
    path('minuscart/', minus_cart),
    path('removecart/', remove_cart),
    path('add-to-cart/', add_to_cart, name='add-to-cart'),
    path('checkout/', checkout, name='checkout'),
    path('paymentdone/', payment_done, name='paymentdone'),

    path('orders/',orders,name="invoice"),
    path('notifications/',notifications,name="notifications"),
    path('order_detail/<id>/',order_detail,name="order_detail"),
    path('seller_order/',seller_orders,name="seller_order"),

    
]

settings/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("product.urls")),
    path('',include("accounts.urls")),
    path('',include("users.urls")),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users.views import *

app_name="user"

urlpatterns = [
    path('user_info/<id>/',buyer_view,name="user_info"),
    # path('user_notifications/<id>/',buyer_notification,name="user_notf"),
    # path('user_invoice/<id>/',buyer_invoice,name="user_invoice"),
    path('user_adress/<id>/',buyer_adress,name="user_adress"),
    
    path('seller_dashboard/<id>/',seller_dashboard,name ='seller_dashboard'),
    path("seller_product/<id>/",seller_product,name="seller_product"),
    # path("seller_order/<id>/",seller_order,name="seller_order"),
    path("store_seller/<id>/",store_view,name="store_view"),
    path("add_product/<id>/",add_product,name="add_product"),
    path("vendor_settings/<id>/",vendor_set,name="vendor_settings"),
    # path("seller_withdraw/<id>/",withdraw,name="withdraw"),
    path("vendor_about/<id>/",store_about,name="store_about"),
    path('seller_payment/',seller_payment,name="seller_payment")

    ]

templates/user/user_buyer/address/addresses.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
    <main class="ps-page--my-account">
        <div class="ps-breadcrumb">
            <div class="container">
                <ul class="breadcrumb">
                    <li><a href="index.html">Home</a></li>
                    <li><a href="user-information.html">Account</a></li>
                    <li>Addresses</li>
                </ul>
            </div>
        </div>
        <section class="ps-section--account">
            <div class="container">
                <div class="row">
                    <div class="col-lg-4">
                        <div class="ps-section__left">
                            <aside class="ps-widget--account-dashboard">
                                <div class="ps-widget__header"><img src="img/users/3.jpg" alt="" />
                                    <figure>
                                        <figcaption>Hello</figcaption>
                                        <p><a href="#"><span class="__cf_email__" data-cfemail="a1d4d2c4d3cfc0ccc4e1c6ccc0c8cd8fc2cecc">[email&#160;protected]</span></a></p>
                                    </figure>
                                </div>
                                <div class="ps-widget__content">
                                    <ul>
                                        <li><a href="{% url 'user:user_info' request.user.id %}"><i class="icon-user"></i> Account Information</a></li>
                                        <li><a href="{% url 'user:user_notf' request.user.id %}"><i class="icon-alarm-ringing"></i> Notifications</a></li>
                                        <li><a href="{% url 'user:user_invoice' request.user.id %}"><i class="icon-papers"></i> Invoices</a></li>
                                        <li class="active"><a href="#"><i class="icon-map-marker"></i> Address</a></li>
                                        {% comment %} <li><a href="#"><i class="icon-store"></i> Recent Viewed Product</a></li> {% endcomment %}
                                        <li><a href="{% url 'user:user_wishlist' request.user.id %}"><i class="icon-heart"></i> Wishlist</a></li>
                                        <li><a href="{% url 'accounts:logout' %}"><i class="icon-power-switch"></i>Logout</a></li>
                                    </ul>
                                </div>
                            </aside>
                        </div>
                    </div>
                    <div class="col-lg-8">
                        <div class="ps-section__right">
                            <div class="ps-section--account-setting">
                                <div class="ps-section__header">
                                    <h3>Address</h3>
                                </div>
                                <div class="ps-section__content">
                                    <div class="row">
                                        <div class="col-md-6 col-12">
                                            <figure class="ps-block--address">
                                                <figcaption>Billing address</figcaption>
                                                <div class="ps-block__content">
                                                    <p>You Have Not Set Up This Type Of Address Yet.</p>
                                                    <ul>
                                                        <li>city: baku</li>
                                                        <li>country: aze</li>
                                                        <li>stret: xknsdf</li>
                                                    </ul>
                                                    <a href="edit-address.html">Edit</a>
                                                </div>
                                            </figure>
                                        </div>
                                        <div class="col-md-6 col-12">
                                            <figure class="ps-block--address">
                                                <figcaption>Shipping address</figcaption>
                                                <div class="ps-block__content">
                                                    <p>You Have Not Set Up This Type Of Address Yet.</p><a href="edit-address.html">Edit</a>
                                                </div>
                                            </figure>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <div class="ps-newsletter">
            <div class="ps-container">
                <form class="ps-form--newsletter" action="http://nouthemes.net/html/martfury/do_action" method="post">
                    <div class="row">
                        <div class="col-xl-5 col-lg-12 col-md-12 col-sm-12 col-12 ">
                            <div class="ps-form__left">
                                <h3>Newsletter</h3>
                                <p>Subcribe to get information about products and coupons</p>
                            </div>
                        </div>
                        <div class="col-xl-7 col-lg-12 col-md-12 col-sm-12 col-12 ">
                            <div class="ps-form__right">
                                <div class="form-group--nest">
                                    <input class="form-control" type="email" placeholder="Email address">
                                    <button class="ps-btn">Subscribe</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </main>
    {% endblock body %}