accounts/urls.py
from django.urls import path,re_path
from .views import *
from django.contrib.auth import views as auth_views
app_name = 'accounts'
urlpatterns = [
    # path(r'^company-edit/$', company_edit_view, name='company-edit'),
	path('register/',register,name="register"),
    path('login/', login_view, name='login'),
    # path(r'^update-profile/$', update_profile_view, name='update_profile_view'),
    # path(r'^my-account/$',account_view,name="account_view"),
    # path(r'^user-list/$',user_list_view,name="user_list_view"),
    # path(r'^user/(?P<slug>.*)/$', user_update, name='user_update'),
    path('logout/',logout_view,name='logout'),
    path('activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/',
        activate, name='activate'),
]

product/urls.py
from django.urls import path
from product.views import *

app_name = "product"
urlpatterns = [
    path('',index_view,name="index"),
    path('api_view',view_api,name="view_api"),
    path('api_view/<id>/',detail_api,name="detail_api"),
    path('product_detail/<slug>/',product_detail,name="product_detail"),
    path('product_delete/<id>/',delete_product,name="delete_product"),
    path("wish/",wishlist_view, name="wish"),
    path('user_wishlist/',wishlist_product_view,name="user_wishlist"),
    path('cart/', show_cart, name='showcart'),
    path('pluscart/', plus_cart),
    path('minuscart/', minus_cart),
    path('removecart/', remove_cart),
    path('add-to-cart/', add_to_cart, name='add-to-cart'),
    path('checkout/', checkout, name='checkout'),
    path('paymentdone/', payment_done, name='paymentdone'),

    path('orders/',orders,name="invoice"),
    path('notifications/',notifications,name="notifications"),
    path('order_detail/<id>/',order_detail,name="order_detail"),
    path('seller_order/',seller_orders,name="seller_order"),

    
]

settings/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("product.urls")),
    path('',include("accounts.urls")),
    path('',include("users.urls")),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users.views import *

app_name="user"

urlpatterns = [
    path('user_info/<id>/',buyer_view,name="user_info"),
    # path('user_notifications/<id>/',buyer_notification,name="user_notf"),
    # path('user_invoice/<id>/',buyer_invoice,name="user_invoice"),
    path('user_adress/<id>/',buyer_adress,name="user_adress"),
    
    path('seller_dashboard/<id>/',seller_dashboard,name ='seller_dashboard'),
    path("seller_product/<id>/",seller_product,name="seller_product"),
    # path("seller_order/<id>/",seller_order,name="seller_order"),
    path("store_seller/<id>/",store_view,name="store_view"),
    path("add_product/<id>/",add_product,name="add_product"),
    path("vendor_settings/<id>/",vendor_set,name="vendor_settings"),
    # path("seller_withdraw/<id>/",withdraw,name="withdraw"),
    path("vendor_about/<id>/",store_about,name="store_about"),
    path('seller_payment/',seller_payment,name="seller_payment")

    ]

users/models.py
from django.db import models
from ckeditor.fields import RichTextField
from accounts.models import MyUser


# Create your models here.


class Vendor(models.Model):
    name=models.CharField(max_length=50)
    image = models.ImageField(upload_to="Vendor_Img",null=True,blank=True)
    email = models.EmailField(null=True,blank=True)
    description = RichTextField(null=True,blank=True)
    seller = models.ForeignKey(MyUser,on_delete=models.CASCADE,related_name="seller_vendor")
    street_1 = models.CharField(max_length=200,null=True,blank=True)
    street_2 = models.CharField(max_length=200,null=True,blank=True)
    city = models.CharField(max_length=100,null=True,blank=True)
    country = models.CharField(max_length=100,null=True,blank=True)
    zip = models.CharField(max_length=100,null=True,blank=True)
    phone_number = models.CharField(max_length=100,null=True,blank=True)




    

    def __str__(self):
        return self.name
    

users/views.py
from itertools import product
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.conf import settings
from django.contrib import messages
from django.utils import timezone
from users.forms import *
from django.contrib.sites.shortcuts import get_current_site
from product.models import Product,ProductImage


# Create your views here.

def buyer_view(request,id):
    context = {}

    usr = get_object_or_404(User, id=id)
    form_b="Buyer"
    form_s="Seller"

    if request.method == 'POST' and 'btn_buyer' in request.POST:
        form = BuyerDetailForm(request.POST, request.FILES or None, instance=usr)
        if form.is_valid():
            form.save()
            messages.success(request, 'Sizin postunuz uğurla yeniləndi!')
            return HttpResponseRedirect('/')
    else:
        form_b = BuyerDetailForm(instance=usr)






        

    if request.method == 'POST' and 'btn_seller' in request.POST:
        form = SellerDetailForm(request.POST, request.FILES or None, instance=usr)
        if form.is_valid():
            form.save()
            messages.success(request, 'Sizin postunuz uğurla yeniləndi!')
            return HttpResponseRedirect('/')
    else:
        form_s = SellerDetailForm(instance=usr)

    context['form_s'] = form_s
    context['form_b'] = form_b
    

    

    return render(request,"user/user_information/user_information.html",context)


# def buyer_notification(request,id):
#     usr = get_object_or_404(User, id=id)

#     return render(request,"user/user_buyer/notifications/notifications.html")

# def buyer_invoice(request,id):
#     usr = get_object_or_404(User, id=id)

#     return render(request,"user/user_buyer/invoice/invoices.html")

# def buyer_wishlist(request,id):
#     usr = get_object_or_404(User, id=id)

#     return render(request,"user/user_buyer/wishlist/whishlist.html")


def buyer_adress(request,id):
    usr = get_object_or_404(User, id=id)

    return render(request,"user/user_buyer/address/addresses.html")



def seller_dashboard(request,id):
    usr = get_object_or_404(User, id=id)

    return render(request,"user/user_seller/seller.html")



def seller_view(request,id):
    context = {}

    usr = get_object_or_404(User, id=id)

    if request.method == 'POST':
        form = SellerDetailForm(request.POST, request.FILES or None, instance=usr)
        if form.is_valid():
            
            
            form.save()
            messages.success(request, 'Sizin postunuz uğurla yeniləndi!')
            return HttpResponseRedirect('/buyer/')
        else:
            context['form'] = form

    context['form'] = SellerDetailForm(instance=usr)


    return render(request,"user/user_information/user_buyer.html",context)



def seller_product(request,id):
    context = {}

    usr = get_object_or_404(User, id=id)

    if request.method == 'POST':

        form = AddProductForm(request.POST, request.FILES or None)
        if form.is_valid():
            form = form.save(commit=False)
            form.seller = usr
            form.save()
            messages.success(request, 'Sizin postunuz uğurla yeniləndi!')
            return redirect(request.META['HTTP_REFERER'])
        else:
            context['form'] = form

    context['form'] = AddProductForm()

    products = Product.objects.filter(seller=usr)
    context['products'] = products




    return render(request,"user/user_seller/seller_product.html",context)

def add_product(request,id):
    context = {}
    
    usr = get_object_or_404(User, id=id)

    if request.method == 'POST':
        images = request.FILES.getlist("image", None)
        form = AddProductForm(request.POST, request.FILES or None)
        if form.is_valid() and images:
            print("I am in is vaild")
            form = form.save(commit=False)
            form.seller = usr
            form.save()
            messages.success(request, 'Sizin postunuz uğurla yeniləndi!')
            for image in images:
                ProductImage.objects.create(
                    product=form, image=image
                )
            # return redirect(request.META['HTTP_REFERER'])
            return redirect("product:index")
        else:
            context['form'] = form

    context['form'] = AddProductForm()

    return render(request,"user/user_seller/add_product.html",context)


# def seller_order(request,id):
#     return render(request,"user/user_seller/seller_orders.html")


def store_view(request,id):
    context = {}
    seller = get_object_or_404(User,id=id)
    store = get_object_or_404(Vendor,seller_id=seller.id)
    
    products = Product.objects.filter(seller=seller)
    context['store'] = store
    context['products'] = products
    return render(request,"user/user_seller/store_detail.html",context)

def store_about(request,id):
    context = {}
    seller = get_object_or_404(User,id=id)
    store = get_object_or_404(Vendor,seller_id=seller.id)
    
    products = Product.objects.filter(seller=seller)
    context['store'] = store
    context['products'] = products
    return render(request,"user/user_seller/store_detail_about.html",context)


def vendor_set(request,id):
    context = {}
    usr = get_object_or_404(User, id=id)
    store = get_object_or_404(Vendor,seller_id=usr.id)
    
    

    if request.method == 'POST':
        form = VendorForm(request.POST, request.FILES or None ,instance=store)
        if form.is_valid():
            form.save()
            messages.success(request, 'Sizin postunuz uğurla yeniləndi!')
            return HttpResponseRedirect('/')
    else:
        form = VendorForm(instance=store)

    context['form'] = form

    return render(request,"user/user_seller/vendor_settings.html",context)


def seller_payment(request):
    return render(request,"user/user_seller/seller_payment.html")


# def withdraw(requets,id):
#     return render(request,"user/user_seller/seller_withdraw.html")


templates/user/user_information/user_information.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block body %}
    <main class="ps-page--my-account">
        <div class="ps-breadcrumb">
            <div class="container">
                <ul class="breadcrumb">
                    <li><a href="index.html">Home</a></li>
                    <li>User Information</li>
                </ul>
            </div>
        </div>
        <section class="ps-section--account">
            <div class="container">
                <div class="row">
                    <div class="col-lg-4">
                        <div class="ps-section__left">
                            <aside class="ps-widget--account-dashboard">
                                <div class="ps-widget__header">
                                    <img style="object-fit:cover;" src="{{request.user.get_avatar}}" alt="">
                                    
                                    <figure>
                                        <figcaption>Hello {{request.user.first_name}}</figcaption>
                                        <p><a href="#"><span class="__cf_email__">{{request.user.email}}</span></a></p>
                                    </figure>
                                </div>
                                <div class="ps-widget__content">
                                    <ul>
                                        <li class="active"><a href="#"><i class="icon-user"></i> Account Information</a></li>
                                        <li><a href="{% url 'product:notifications' %}"><i class="icon-alarm-ringing"></i> Notifications</a></li>
                                        <li><a href="{% url 'product:invoice' %}"><i class="icon-papers"></i> Invoices</a></li>
                                        {% comment %} <li><a href="{% url 'user:user_adress' request.user.id %}"><i class="icon-map-marker"></i> Address</a></li> {% endcomment %}
                                        <li><a href="#"><i class="icon-store"></i> Recent Viewed Product</a></li>
                                        <li><a href="{% url 'product:user_wishlist' %}"><i class="icon-heart"></i> Wishlist</a></li>
                                        <li><a href="{% url 'accounts:logout' %}"><i class="icon-power-switch"></i>Logout</a></li>
                                    </ul>
                                </div>
                            </aside>
                        </div>
                    </div>
                    <div class="col-lg-8">
                        <div class="ps-section__right">
                            {% if request.user.is_buyer %}
                            <form class="ps-form--account-setting" action="" method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="ps-form__header">
                                    <h3> User Information</h3>
                                </div>
                                
                                <div class="ps-form__content">
                                    <div class="form-group">
                                        {{form_b.first_name|as_crispy_field}}
                                    </div>
                                    <div class="row">
                                        <div class="col-sm-6">
                                            <div class="form-group">
                                                {{form_b.last_name|as_crispy_field}}
                                            </div>
                                        </div>
                                        <div class="col-sm-6">
                                            <div class="form-group">
                                                {{form_b.email|as_crispy_field}}
                                            </div>
                                        </div>
                                        <div class="col-sm-6">
                                            <div class="form-group">
                                                {{form_b.birthday|as_crispy_field}}
                                            </div>
                                        </div>
                                        <div class="col-sm-6">
                                            <div class="form-group">
                                               {{form_b.phone_number|as_crispy_field}}
                                            </div>
                                        </div>
                                        <div class="col-sm-6">
                                            <div class="form-group">
                                               {{form_b.image|as_crispy_field}}
                                            </div>
                                        </div>
                                        <div class="col-sm-6">
                                            <div class="form-group">
                                               {{form_b.usertype|as_crispy_field}}
                                            </div>
                                        </div>
                                        <div class="form-group submit">
                                            <button class="ps-btn" name="btn_buyer">Update</button>
                                        </div>
                                    </div>
                                </div>
                                
                            </form>
                            {% endif %}
                            {% if request.user.is_seller %}
                            <form class="ps-form--account-setting" action="" method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="ps-form__header">
                                    <h3> User Information</h3>
                                </div>
                                
                                <div class="ps-form__content">
                                    <div class="form-group">
                                        {{form_s.first_name|as_crispy_field}}
                                    </div>
                                    <div class="row">
                                        <div class="col-sm-6">
                                            <div class="form-group">
                                                {{form_s.last_name|as_crispy_field}}
                                            </div>
                                        </div>
                                        <div class="col-sm-6">
                                            <div class="form-group">
                                                {{form_s.email|as_crispy_field}}
                                            </div>
                                        </div>
                                        <div class="col-sm-6">
                                            <div class="form-group">
                                                {{form_s.birthday|as_crispy_field}}
                                            </div>
                                        </div>
                                        <div class="col-sm-6">
                                            <div class="form-group">
                                               {{form_s.phone_number|as_crispy_field}}
                                            </div>
                                        </div>
                                        <div class="col-sm-6">
                                            <div class="form-group">
                                               {{form_s.image|as_crispy_field}}
                                            </div>
                                        </div>
                                        <div class="col-sm-6">
                                            <div class="form-group">
                                               {{form_s.usertype|as_crispy_field}}
                                            </div>
                                        </div>
                                        <div class="col-sm-6">
                                            <div class="form-group">
                                               {{form_s.company_name|as_crispy_field}}
                                            </div>
                                        </div>
                                        <div class="col-sm-6">
                                            <div class="form-group">
                                               <input type="hidden">
                                            </div>
                                        </div>
                                        <div class="form-group submit">
                                            <button class="ps-btn" name="btn_seller">Update</button>
                                        </div>
                                    </div>
                                </div>
                            </form>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <div class="ps-newsletter">
            <div class="ps-container">
                <form class="ps-form--newsletter" action="" method="post">
                    <div class="row">
                        <div class="col-xl-5 col-lg-12 col-md-12 col-sm-12 col-12 ">
                            <div class="ps-form__left">
                                <h3>Newsletter</h3>
                                <p>Subcribe to get information about products and coupons</p>
                            </div>
                        </div>
                        <div class="col-xl-7 col-lg-12 col-md-12 col-sm-12 col-12 ">
                            <div class="ps-form__right">
                                <div class="form-group--nest">
                                    <input class="form-control" type="email" placeholder="Email address">
                                    <button class="ps-btn">Subscribe</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </main>
{% endblock body %}