accounts/urls.py
from django.urls import path,re_path
from .views import *
from django.contrib.auth import views as auth_views
app_name = 'accounts'
urlpatterns = [
    # path(r'^company-edit/$', company_edit_view, name='company-edit'),
	path('register/',register,name="register"),
    path('login/', login_view, name='login'),
    # path(r'^update-profile/$', update_profile_view, name='update_profile_view'),
    # path(r'^my-account/$',account_view,name="account_view"),
    # path(r'^user-list/$',user_list_view,name="user_list_view"),
    # path(r'^user/(?P<slug>.*)/$', user_update, name='user_update'),
    path('logout/',logout_view,name='logout'),
    path('activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/',
        activate, name='activate'),
]

product/urls.py
from django.urls import path
from product.views import *

app_name = "product"
urlpatterns = [
    path('',index_view,name="index"),
    path('api_view',view_api,name="view_api"),
    path('api_view/<id>/',detail_api,name="detail_api"),
    path('product_detail/<slug>/',product_detail,name="product_detail"),
    path('product_delete/<id>/',delete_product,name="delete_product"),
    path("wish/",wishlist_view, name="wish"),
    path('user_wishlist/',wishlist_product_view,name="user_wishlist"),
    path('cart/', show_cart, name='showcart'),
    path('pluscart/', plus_cart),
    path('minuscart/', minus_cart),
    path('removecart/', remove_cart),
    path('add-to-cart/', add_to_cart, name='add-to-cart'),
    path('checkout/', checkout, name='checkout'),
    path('paymentdone/', payment_done, name='paymentdone'),

    path('orders/',orders,name="invoice"),
    path('notifications/',notifications,name="notifications"),
    path('order_detail/<id>/',order_detail,name="order_detail"),
    path('seller_order/',seller_orders,name="seller_order"),

    
]

settings/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("product.urls")),
    path('',include("accounts.urls")),
    path('',include("users.urls")),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users.views import *

app_name="user"

urlpatterns = [
    path('user_info/<id>/',buyer_view,name="user_info"),
    # path('user_notifications/<id>/',buyer_notification,name="user_notf"),
    # path('user_invoice/<id>/',buyer_invoice,name="user_invoice"),
    path('user_adress/<id>/',buyer_adress,name="user_adress"),
    
    path('seller_dashboard/<id>/',seller_dashboard,name ='seller_dashboard'),
    path("seller_product/<id>/",seller_product,name="seller_product"),
    # path("seller_order/<id>/",seller_order,name="seller_order"),
    path("store_seller/<id>/",store_view,name="store_view"),
    path("add_product/<id>/",add_product,name="add_product"),
    path("vendor_settings/<id>/",vendor_set,name="vendor_settings"),
    # path("seller_withdraw/<id>/",withdraw,name="withdraw"),
    path("vendor_about/<id>/",store_about,name="store_about"),
    path('seller_payment/',seller_payment,name="seller_payment")

    ]

users/models.py
from django.db import models
from ckeditor.fields import RichTextField
from accounts.models import MyUser


# Create your models here.


class Vendor(models.Model):
    name=models.CharField(max_length=50)
    image = models.ImageField(upload_to="Vendor_Img",null=True,blank=True)
    email = models.EmailField(null=True,blank=True)
    description = RichTextField(null=True,blank=True)
    seller = models.ForeignKey(MyUser,on_delete=models.CASCADE,related_name="seller_vendor")
    street_1 = models.CharField(max_length=200,null=True,blank=True)
    street_2 = models.CharField(max_length=200,null=True,blank=True)
    city = models.CharField(max_length=100,null=True,blank=True)
    country = models.CharField(max_length=100,null=True,blank=True)
    zip = models.CharField(max_length=100,null=True,blank=True)
    phone_number = models.CharField(max_length=100,null=True,blank=True)




    

    def __str__(self):
        return self.name
    

users/views.py
from itertools import product
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.conf import settings
from django.contrib import messages
from django.utils import timezone
from users.forms import *
from django.contrib.sites.shortcuts import get_current_site
from product.models import Product,ProductImage


# Create your views here.

def buyer_view(request,id):
    context = {}

    usr = get_object_or_404(User, id=id)
    form_b="Buyer"
    form_s="Seller"

    if request.method == 'POST' and 'btn_buyer' in request.POST:
        form = BuyerDetailForm(request.POST, request.FILES or None, instance=usr)
        if form.is_valid():
            form.save()
            messages.success(request, 'Sizin postunuz uğurla yeniləndi!')
            return HttpResponseRedirect('/')
    else:
        form_b = BuyerDetailForm(instance=usr)






        

    if request.method == 'POST' and 'btn_seller' in request.POST:
        form = SellerDetailForm(request.POST, request.FILES or None, instance=usr)
        if form.is_valid():
            form.save()
            messages.success(request, 'Sizin postunuz uğurla yeniləndi!')
            return HttpResponseRedirect('/')
    else:
        form_s = SellerDetailForm(instance=usr)

    context['form_s'] = form_s
    context['form_b'] = form_b
    

    

    return render(request,"user/user_information/user_information.html",context)


# def buyer_notification(request,id):
#     usr = get_object_or_404(User, id=id)

#     return render(request,"user/user_buyer/notifications/notifications.html")

# def buyer_invoice(request,id):
#     usr = get_object_or_404(User, id=id)

#     return render(request,"user/user_buyer/invoice/invoices.html")

# def buyer_wishlist(request,id):
#     usr = get_object_or_404(User, id=id)

#     return render(request,"user/user_buyer/wishlist/whishlist.html")


def buyer_adress(request,id):
    usr = get_object_or_404(User, id=id)

    return render(request,"user/user_buyer/address/addresses.html")



def seller_dashboard(request,id):
    usr = get_object_or_404(User, id=id)

    return render(request,"user/user_seller/seller.html")



def seller_view(request,id):
    context = {}

    usr = get_object_or_404(User, id=id)

    if request.method == 'POST':
        form = SellerDetailForm(request.POST, request.FILES or None, instance=usr)
        if form.is_valid():
            
            
            form.save()
            messages.success(request, 'Sizin postunuz uğurla yeniləndi!')
            return HttpResponseRedirect('/buyer/')
        else:
            context['form'] = form

    context['form'] = SellerDetailForm(instance=usr)


    return render(request,"user/user_information/user_buyer.html",context)



def seller_product(request,id):
    context = {}

    usr = get_object_or_404(User, id=id)

    if request.method == 'POST':

        form = AddProductForm(request.POST, request.FILES or None)
        if form.is_valid():
            form = form.save(commit=False)
            form.seller = usr
            form.save()
            messages.success(request, 'Sizin postunuz uğurla yeniləndi!')
            return redirect(request.META['HTTP_REFERER'])
        else:
            context['form'] = form

    context['form'] = AddProductForm()

    products = Product.objects.filter(seller=usr)
    context['products'] = products




    return render(request,"user/user_seller/seller_product.html",context)

def add_product(request,id):
    context = {}
    
    usr = get_object_or_404(User, id=id)

    if request.method == 'POST':
        images = request.FILES.getlist("image", None)
        form = AddProductForm(request.POST, request.FILES or None)
        if form.is_valid() and images:
            print("I am in is vaild")
            form = form.save(commit=False)
            form.seller = usr
            form.save()
            messages.success(request, 'Sizin postunuz uğurla yeniləndi!')
            for image in images:
                ProductImage.objects.create(
                    product=form, image=image
                )
            # return redirect(request.META['HTTP_REFERER'])
            return redirect("product:index")
        else:
            context['form'] = form

    context['form'] = AddProductForm()

    return render(request,"user/user_seller/add_product.html",context)


# def seller_order(request,id):
#     return render(request,"user/user_seller/seller_orders.html")


def store_view(request,id):
    context = {}
    seller = get_object_or_404(User,id=id)
    store = get_object_or_404(Vendor,seller_id=seller.id)
    
    products = Product.objects.filter(seller=seller)
    context['store'] = store
    context['products'] = products
    return render(request,"user/user_seller/store_detail.html",context)

def store_about(request,id):
    context = {}
    seller = get_object_or_404(User,id=id)
    store = get_object_or_404(Vendor,seller_id=seller.id)
    
    products = Product.objects.filter(seller=seller)
    context['store'] = store
    context['products'] = products
    return render(request,"user/user_seller/store_detail_about.html",context)


def vendor_set(request,id):
    context = {}
    usr = get_object_or_404(User, id=id)
    store = get_object_or_404(Vendor,seller_id=usr.id)
    
    

    if request.method == 'POST':
        form = VendorForm(request.POST, request.FILES or None ,instance=store)
        if form.is_valid():
            form.save()
            messages.success(request, 'Sizin postunuz uğurla yeniləndi!')
            return HttpResponseRedirect('/')
    else:
        form = VendorForm(instance=store)

    context['form'] = form

    return render(request,"user/user_seller/vendor_settings.html",context)


def seller_payment(request):
    return render(request,"user/user_seller/seller_payment.html")


# def withdraw(requets,id):
#     return render(request,"user/user_seller/seller_withdraw.html")


templates/user/user_seller/seller.html
 {% extends 'base.html' %}
{% load static %}

{% block body %}

    <section id="dashboardHero">
       <div class="container">
        <div class="heading-dashboard">
            <h2>Dashboard</h2>
       </div>
       <div class="dashboard-body">
        <div class="row">
            <div class="col-md-3">
                <div class="sidebar">
                  <ul class="list-dashboard">
            
            
                    <li class="d-flex justify-content-center active-dashboard common-lies w-100">
                        <a href="{% url 'user:seller_dashboard' request.user.id %}"><i class="fas fa-tachometer-alt icons"></i>Dashboard</a>
                        
                        </li>
                    <li class="d-flex justify-content-center other-lies common-lies">
                        <a href="{% url 'user:seller_product' request.user.id %}"><i class="fas fa-briefcase icons"></i>Products</a>
                        
                    <li class="d-flex justify-content-center other-lies common-lies">
                        <a href="{% url 'product:seller_order' %}"><i class="fas fa-shopping-cart icons"></i>Orders</a>
                        
                    </li>
                    <li class="d-flex justify-content-center other-lies common-lies">
                        <a href="{% url 'user:vendor_settings' request.user.id %}"><i class="fas fa-cog icons"></i>Settings</a>
                        
                    </li>
                    <li class="d-flex justify-content-center other-lies">
                        <button><a href="{% url 'user:store_view' request.user.id %}" title="Visit Store"><i class="fas fa-external-link-alt"></i></a></button>
                        <button><a href="{% url 'user:user_info' request.user.id %}"><i class="fas fa-user"></i></a></button>
                        <button><a href="{% url 'accounts:logout' %}"><i class="fa-solid fa-power-off"></i></a></button>
                    </li>
                </ul>
                  
                </div>
                </div>
            <div class="col-md-5">
                <div class="alert alert-danger" role="alert">
                    Error! Your account is not enabled for selling, please contact the admin
                  </div>
                    <div class="statistics">
                        <div class="sales ">
                            <span>Sales</span>
                            <p>$0.00</p>
                        </div>
                        <div class="earings">
                            <span>Earing</span>
                            <p>$0.00</p>
                        </div>
                        <div class="page-view">
                            <span>Pageview</span>
                            <p>0</p>
                        </div>
                        <div class="order">
                            <span>Order</span>
                            <p>0</p>
                        </div>
                    </div>
                    
                       
            </div>
            <div class="col-md-4">
                <div class="orders">
                    <div class="heading-orders">
                        <i class="fas fa-shopping-cart"></i>
                        <span>Orders</span>
                    </div>
                    <div class="details">
                        <ul class="detail-list">
                            <li class="detail-row d-flex justify-content-center mt-3">
                                <span>Total</span>
                                <span>0</span>
                            </li>
                            <li class="detail-row d-flex justify-content-center mt-3">
                                <span>Complated</span>
                                <span>0</span>
                            </li>
                            <li class="detail-row d-flex justify-content-center mt-3">
                                <span>Pending</span>
                                <span>0</span>
                            </li>
                            <li class="detail-row d-flex justify-content-center mt-3">
                                <span>Processing</span>
                                <span>0</span>
                            </li>
                            <li class="detail-row d-flex justify-content-center mt-3">
                                <span>Cancelled</span>
                                <span>0</span>
                            </li>
                            <li class="detail-row d-flex justify-content-center mt-3">
                                <span>Refounded</span>
                                <span>0</span>
                            </li>
                            <li class="detail-row d-flex justify-content-center mt-3">
                                <span>On Hold</span>
                                <span>0</span>
                            </li>
                        </ul>
                    </div>
                 
                </div>
                <div class="products">
                    <div class="heading-products">
                     
                        <div class="left-content">
                            <i class="fas fa-briefcase" aria-hidden="true"></i>
                            <span>Products</span>
                        </div>
                        <div class="right-content">
                            <span>+ Add new product</span>
                        </div>
                       
                    </div>
                    <div class="details-products">
                        <ul class="detail-product-list">
                            <li class="detail-row d-flex justify-content-center mt-3">
                                <span>Total</span>
                                <span>0</span>
                            </li>
                            <li class="detail-row d-flex justify-content-center mt-3">
                                <span>Live</span>
                                <span>0</span>
                            </li>   
                            <li class="detail-row d-flex justify-content-center mt-3">
                                <span>Ofline</span>
                                <span>0</span>
                            </li>   
                            <li class="detail-row d-flex justify-content-center mt-3">
                                <span>Pending Review</span>
                                <span>0</span>
                            </li>   
                        </ul>
                    </div>
                </div>

            </div>
        </div>
       </div>
       </div>


    </section>
  
    
    
{% endblock body %} 




    

templates/user/user_seller/seller_orders.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block body %}
     <div class="ps-page--single">
        <div class="ps-breadcrumb">
            <div class="container">
                <ul class="breadcrumb">
                    <li><a href="index.html">Home</a></li>
                    <li><a href="index.html">Pages</a></li>
                    <li><a href="vendor-store.html">Vendor Pages</a></li>
                    <li>Vendor Dashboard Free</li>
                </ul>
            </div>
        </div>
    </div>
  <div class="ps-vendor-dashboard">
        <div class="container">
            <div class="ps-section__header">
                <h3>Dasboard</h3>
               
            </div>
          
        </div>
    </div> 
    
    <div class="free_bigdiv">
       <div class="free_middiv">
        <div class="col-md-3">
          <div class="sidebar">
            <ul class="list-dashboard">
      
      
              <li class="d-flex justify-content-center other-lies  common-lies w-100">
                  <a href="{% url 'user:seller_dashboard' request.user.id %}"><i class="fas fa-tachometer-alt icons"></i>Dashboard</a>
                  
                  </li>
              <li class="d-flex justify-content-center other-lies common-lies">
                  <a href="{% url 'user:seller_product' request.user.id %}"><i class="fas fa-briefcase icons"></i>Products</a>
                  
              <li class="d-flex justify-content-center active-dashboard common-lies">
                  <a href="{% url 'product:seller_order' %}"><i class="fas fa-shopping-cart icons"></i>Orders</a>
                  
              </li>
              <li class="d-flex justify-content-center other-lies common-lies">
                  <a href="{% url 'user:vendor_settings' request.user.id %}"><i class="fas fa-cog icons"></i>Settings</a>
                  
              </li>
              <li class="d-flex justify-content-center other-lies">
                <button><a href="{% url 'user:store_view' request.user.id %}" title="Visit Store"><i class="fas fa-external-link-alt"></i></a></button>
                <button><a href="{% url 'user:user_info' request.user.id %}"><i class="fas fa-user"></i></a></button>
                <button><a href="{% url 'accounts:logout' %}"><i class="fa-solid fa-power-off"></i></a></button>
              </li>
          </ul>
            
          </div>
          </div>
         <div class="free_div2">
            <!-- <div class="free_error">
                <p><b>Error!</b> Your account is not enabled for selling, please contact the admin</p>
            </div>
            <div class="free_orders">
              <ul>
                <li><a href="#">All(0) |</a></li>
                 <li><a href="#">Completed(0) |</a></li>
                 <li><a href="#">Processing(0) |</a></li>
                 <li><a href="#">On-hold(0) |</a></li>
                 <li><a href="#">Pending(0) |</a></li>
                 <li><a href="#">Canselled(0) |</a></li>
                 <li><a href="#">Refunded(0) |</a></li>
                 <li><a href="#">Failed(0) |</a></li>
              </ul>
               
            </div>
            <div class="free_orders_big">
                <button>Filter</button>
                <input placeholder='search orders'/>
                <input placeholder='search range orders'/>
                <button>Filter</button>
                <button>Reset</button>
                <button>Expert all</button>
                <button>Expert Filtered</button>
            </div>
            <div class="free_orders_mid">
                 No orders found
            </div > -->
            <div class="list-group">
              <div id="order-div">
                <div id="order-div-head">
                  <div>
                    Product Information
                  </div>
                  <div>
                    Price
                  </div>
                  <div>
                    Status
                  </div>
                  <div>
                    Data and Time
                  </div>
                </div>
              <div id="orders">

              
                {% for order in orders %}
                <div class="order">
                  <div>
                    <h5 class="order-customer">
                      <i class="fa-solid fa-user"></i> {{order.customer.first_name}} {{order.customer.last_name}}
                    </h5>
                    <h5 class="order-address">
                      <i class="fa-solid fa-location-dot"></i>
                    </h5>
                    <h5 class="order-mail">
                      <i class="fa-solid fa-envelope"></i> {{order.customer.email}}
                    </h5>
                    <h5>
                      Name : {{order.product.name}}
                    </h5>
                  </div>
                  <div class="order-price">
                    <span>450$</span>
                  </div>
                  <div class="order-status">
                    Pending
                  </div>
                  <div class="order-date">
                    2022-11-03 13:34:12
                  </div>
                  <div class="order-status-change">
                    <i class="fa-solid fa-ellipsis-vertical"></i>
                    <ul class="order-status-list">
                      <li>Pending</li>
                      <li>Pending</li>
                      <li>Pending</li>
                      <li>Pending</li>
                    </ul>
                  </div>
                </div>
                <!-- <a href="#"  class="list-group-item list-group-item-action active" aria-current="true" style="background-color:forestgreen">
                  <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">#{{order.id}}</h5>
                    <small>3 days ago</small>
                  </div>
                  <p class="mb-1" style="color:black ;">Customer :{{order.customer.first_name}} {{order.customer.last_name}}</p>
                  <p class="mb-1" style="color:black ;">Adress :</p>
                  <p class="mb-1" style="color:black ;">Email :{{order.customer.email}}</p>
                  <h3>Product Name </h3>
                  <p class="mb-1" style="color:black ;">{{order.product.name}}</p>
                  
                  <small>{{order.status}}</small>
                </a> -->
                <!-- Button trigger modal -->
                  <!-- <button type="button" class="btn btn-primary" style="margin-bottom: 30px;" data-bs-toggle="modal" data-bs-target="#exampleModal-{{order.id}}">
                    Edit
                  </button> -->

                {% endfor %}

                <!-- Modal -->
                {% for order in orders%}
                      <div class="modal fade" id="exampleModal-{{order.id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                          <div class="modal-content">
                            <div class="modal-header">
                              <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                              <form action="" method="post">
                                {% csrf_token %}

                                
                                  <input type="hidden" name="smth" value="{{order.id}}">
                                  {{form|crispy}}
                                

                              
                            </div>
                            <div class="modal-footer">
                              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                              <button type="submit" class="btn btn-primary">Save changes</button>
                            </div>
                          </form>
                          </div>
                        </div>
                      </div>
                      {% endfor %}
                
                    </div>
                    </div>
              </div>
            

         </div>
         
      </div>
  </div>

    
    {% endblock body %} 




    

templates/user/user_seller/seller_payment.html
{% extends 'base.html' %}
{% load static %}

{% block body %}





{% endblock body %}


templates/user/user_seller/seller_withdraw.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
     {% comment %} <div class="ps-page--single">
        <div class="ps-breadcrumb">
            <div class="container">
                <ul class="breadcrumb">
                    <li><a href="index.html">Home</a></li>
                    <li><a href="index.html">Pages</a></li>
                    <li><a href="vendor-store.html">Vendor Pages</a></li>
                    <li>Vendor Dashboard Free</li>
                </ul>
            </div>
        </div>
    </div>
  <div class="ps-vendor-dashboard">
        <div class="container">
            <div class="ps-section__header">
                <h3>Dasboard</h3>
               
            </div>
          
        </div>
    </div> 
    
    <div class="free_bigdiv">
       <div class="free_middiv">
         <div class="free_div1">
            
            <ul class="dasbord_ul">
            
                <li><p><i class="fas fa-tachometer-alt"></i>&nbsp;&nbsp;<a href="#">Dashboard</a></p></li>
                <li><p><i class="fas fa-tachometer-alt"></i>&nbsp;&nbsp;<a href="{% url 'user:seller_product' request.user.id %}">Products</a></p></li>
                <li><p><i class="fas fa-tachometer-alt"></i>&nbsp;&nbsp;<a href="{% url 'user:seller_order' request.user.id %}">Order</a></p></li>
                <li><p><i class="fas fa-tachometer-alt"></i>&nbsp;&nbsp;<a h    ref="{% url 'user:withdraw' request.user.id %}">Withdrafts</a></p></li>
                <li><p><i class="fas fa-tachometer-alt"></i>&nbsp;&nbsp;<a href="{% url 'user:vendor_settings' request.user.id %}">Settings</a></p></li>
            </ul>
            <ul class="dasbord_ul1">
                <li><i class="fas fa-external-link-alt"></i></li>
                <li><i class="fas fa-external-link-alt"></i></li>
                <li><i class="fas fa-external-link-alt"></i></li>
            </ul>
           
         </div>
         
         
       </div>
    </div> {% endcomment %}
    {% endblock body %} 




    